### ISSUE TITLE
Store Reprint Visual Asset 

### ISSUE THREAD

**Issue by AidanGuarniere** [Siphon880gh/reprint#9]
- Configure Multer storage system
- Possible GridFS useage

**Comment by Siphon880gh** [comment]
Good news! I chose the Google Cloud server and I'm successful at uploading images on the upload form. However there are other issues such as making sure the filenames are unique, getting the filepath back to mongoose (should be easy), and keeping password secret.

I decided to go with a Cloud server even though the setup may be more complicated than Multer and GridFS because Cloud servers seems to be the future.

**Comment by Siphon880gh** [comment]
Please wait until I figure out how to keep Google server authentication strings secret before adding Mongoose.
